### ISSUE TITLE
Notification tap produces DuckDuckGo 

### ISSUE THREAD

**Issue by alanthehat** [gjedeer/androidwisprclient#10]
Device: Samsung J5
OS: 5.1.1

Just recently when I tap "connected to" notification my default browser comes up on https://duckduckgo.com/ 
This is not the browser's default page.

**Comment by gjedeer** [comment]
It was google.com before, any ideas for a neutral page which doesn't sell your data and is useful? I'm not in love with DDG by any means

**Comment by alanthehat** [comment]
DDG is fine by me, I just don't remember it doing that before & I wasn't expecting it. 
Sorry, my memory is erratic.

**Comment by gjedeer** [comment]
Perhaps that notification should do nothing when clicked, personally i never touched it outside of testing

**Comment by alanthehat** [comment]
I think I was expecting some sort of status page, but DDG makes sense.
