### ISSUE TITLE
Display Week connection areas

### ISSUE THREAD

**Issue by JasonGartner** [gjedeer/androidwisprclient#14]
I have done an analysis of your google reviews for a university project and a large majority of reviews are complaining about bad connection and frequent disconnects. A recommendation would be to add a feature to notify users of weak connection areas on the network. If the users would know upfront that they are in a poor connection area then they might not complain and try to move to a better connection area in order to use the app.

**Comment by gjedeer** [comment]
Please go back to spamming on facebook and not pollute github.
