### ISSUE TITLE
Billing Issues

### ISSUE THREAD

**Issue by JasonGartner** [gjedeer/androidwisprclient#15]
I have done an analysis of your google reviews for a university project and a large majority of reviews are negative and say that the app is a waste of money. One review in particular was saying how billing is a fixed time that starts as soon as you purchase the allocated time. Rather than counting down the clock as soon as a user purchases time it could be better to only count down the clock if a user is actively surfing the web or using data rather than billing them for their phone doing nothing in their pocket. This could improve the reviews and overall user experience.

**Comment by gjedeer** [comment]
Please go back to spamming on facebook and not pollute github.
