### ISSUE TITLE
Tag version 1.5.1

### ISSUE THREAD

**Issue by krt16s** [gjedeer/androidwisprclient#9]
While afee0b45fd5f635b913d6ca2ef43588a6841578cafee0b45fd5f635b913d6ca2ef43588a6841578c seems to be a release of 1.5.1, it hasn't been tagged, yet, and does not appear on https://github.com/gjedeer/androidwisprclient/releases. Maybe your forgot to `git push --tags`?

**Comment by gjedeer** [comment]
I did indeed.Thanks!
